"""Add creator_id and opponent_id

Revision ID: 406dfb25dfcf
Revises: b988a5b642d7
Create Date: 2025-05-09 18:28:06.720970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '406dfb25dfcf'
down_revision: Union[str, None] = 'b988a5b642d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('creator_id', sa.String(), nullable=True))
    op.add_column('rooms', sa.Column('opponent_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'opponent_id')
    op.drop_column('rooms', 'creator_id')
    # ### end Alembic commands ###
