"""update column length for user_name and user_login

Revision ID: 685cab6ab3c8
Revises: 
Create Date: 2025-04-18 17:45:40.824132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '685cab6ab3c8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_id',
               existing_type=sa.UUID(),
               nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.alter_column('users', 'user_password',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'photo_link',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'photo_link',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'user_password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('users', 'user_id',
               existing_type=sa.UUID(),
               nullable=True,
               existing_server_default=sa.text('uuid_generate_v4()'))
    # ### end Alembic commands ###
